/**
 * dsh-engram: compile the shared pure model (client/src/esrModel.ts) to a
 * plain ESM module `lib/esrModel.mjs` so the node test runner can unit-test
 * the client's board/markdown logic without a browser or React harness.
 *
 * Reuses the same harness-resolved esbuild as client/build.mjs — editing that
 * resolver keeps both builds portable (see client/harness.mjs).
 */
import { createRequire } from "node:module";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { esbuildPkg } from "./harness.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");

const pkgDir = esbuildPkg();
if (pkgDir === null) {
  console.error(
    "[dsh-engram build-model] esbuild not found — set DSH_CHECKOUT to a DeepSeek Harness checkout (or install esbuild into node_modules).",
  );
  process.exit(1);
}
const esbuild = createRequire(join(pkgDir, "package.json"))("esbuild");

const result = await esbuild.build({
  entryPoints: [resolve(here, "src/esrModel.ts")],
  bundle: true,
  format: "esm",
  platform: "neutral",
  target: "es2022",
  // Type-only imports only — nothing external is expected.
  external: [],
  write: false,
  minify: false,
  sourcemap: false,
  logLevel: "warning",
  banner: {
    js: "// <autogenerated by client/build-model.mjs — do not edit directly>\n// Compiles client/src/esrModel.ts for the node test runner.",
  },
});

mkdirSync(resolve(root, "lib"), { recursive: true });
const outPath = resolve(root, "lib/esrModel.mjs");
writeFileSync(outPath, result.outputFiles[0].text);
console.log(`wrote ${outPath} (${result.outputFiles[0].text.length} bytes)`);
