// <autogenerated by client/build-model.mjs — do not edit directly>
// Compiles client/src/esrModel.ts for the node test runner.

// client/src/esrModel.ts
function taskGaps(t) {
  const gaps = [];
  if (!t.artifact) gaps.push("artifact");
  if (!t.evaluation) gaps.push("evaluation");
  if (!t.memoryRefs || t.memoryRefs.length === 0) gaps.push("memory_ref");
  return gaps;
}
function shortId(id) {
  return id.length > 12 ? `${id.slice(0, 6)}\u2026${id.slice(-4)}` : id;
}
function blockedBy(t, all) {
  if (t.state === "stable") return 0;
  const open = new Set(all.filter((x) => x.state !== "stable").map((x) => x.id));
  return (t.deps ?? []).filter((d) => d.kind !== "relates-to" && open.has(d.id)).length;
}
function shortAgent(a) {
  if (!a) return "";
  const bare = a.split(/[@#/:\\]+/).pop();
  return bare.replace(/^session[-_]/i, "").replace(/^agent[-_]/i, "").slice(0, 14);
}
function fmtDateShort(ts) {
  return ts ? new Date(ts).toLocaleDateString("zh-CN", { month: "short", day: "numeric" }) : "\u2013";
}
function buildTasksMarkdown(tasks) {
  const esc = (s) => String(s ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");
  const rows = tasks.slice().sort((a, b) => a.state.localeCompare(b.state) || (a.createdAt ?? 0) - (b.createdAt ?? 0)).map((t) => {
    const ev = `${t.artifact ? "artifact\u2713" : "artifact\u2717"} \xB7 ${t.evaluation ? "eval\u2713" : "eval\u2717"} \xB7 ${(t.memoryRefs?.length ?? 0) > 0 ? "ref\u2713" : "ref\u2717"}`;
    return `| ${t.state} | ${esc(t.name)} | ${esc(t.workspace.replace(/^.*[\\/]/, ""))} | ${esc(taskGaps(t).join(", ") || "\u2014")} | ${ev} | ${fmtDateShort(t.createdAt ?? 0)} |`;
  });
  return `# ESR \u4EFB\u52A1\u5BFC\u51FA \xB7 ${(/* @__PURE__ */ new Date()).toISOString().slice(0, 10)}

| \u72B6\u6001 | \u4EFB\u52A1 | \u5DE5\u4F5C\u533A | \u8BC1\u636E\u7F3A\u53E3 | \u8BC1\u636E | \u521B\u5EFA |
|---|---|---|---|---|---|
${rows.join("\n") || "(\u65E0\u4EFB\u52A1)"}`;
}
var POLL_MS = 2e4;
export {
  POLL_MS,
  blockedBy,
  buildTasksMarkdown,
  fmtDateShort,
  shortAgent,
  shortId,
  taskGaps
};
